spring:
  cloud:
    stream:
      bindings:
        receiveMessageFromCvPendingTopic-in-0.destination: cv_pending_topic 
    gcp:
      core:
        enabled: true
      pubsub:
        enabled: true
      project-id: timoxino